name: CI

on:
  schedule:
    # run every day at 4am UTC
    - cron: '0 4 * * *'
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@d68193b68216da64eafaa618f53c59f5d271c56e  # v1.14.0
    with:
      envs: |
        - macos: py310-test-oldestdeps
        - macos: py311-test
        - macos: py312-test
        - linux: py310-test-oldestdeps
        - linux: py311-test
        - linux: py312-test
        - linux: py312-test-devdeps
        - windows: py310-test-oldestdeps
        - windows: py311-test
        - windows: py312-test
      coverage: 'codecov'

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@d68193b68216da64eafaa618f53c59f5d271c56e  # v1.14.0
    with:
      test_extras: test
      test_command: pytest -p no:warnings --pyargs pyregion
      targets: |
        - cp*-manylinux_x86_64
        - cp*-macosx_x86_64
        - cp*-macosx_arm64
        - cp*-win_amd64

    secrets:
      pypi_token: ${{ secrets.pypi_token }}
